<a href="https://colab.research.google.com/github/Dhritidhawan/AI-Assignments/blob/main/Assignment2_DhritiDhawan_1024150370.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

We have a class defined for vehicles.

1. Create two new vehicles called car1 and car2.
2. Set car1 to be a red convertible worth 60,000.00 with a name of Fer
3. Set car2 to be a blue van named Jump worth 10,000.00.

In [ ]:
class Vehicle:
    pass

car1 = Vehicle()
car2 = Vehicle()

car1.name = "Fer"
car1.color = "red"
car1.kind = "convertible"
car1.value = 60000.00

car2.name = "Jump"
car2.color = "blue"
car2.kind = "van"
car2.value = 10000.00

print(car1.color, car1.kind, "named", car1.name, "worth", car1.value)
print(car2.color, car2.kind, "named", car2.name, "worth", car2.value)


red convertible named Fer worth 60000.0
blue van named Jump worth 10000.0


1. Create and Inspect an Array Create a 1D NumPy array containing integers from 10 to 50 (inclusive) with a step of 5. Print its shape, size, and data type.

In [ ]:
arr1 = np.arange(10,51,5)
print("1. Array:", arr1)
print("Shape:", arr1.shape)
print("Size:",arr1.size)
print("Data Type :",arr1.dtype)


1. Array: [10 15 20 25 30 35 40 45 50]
Shape: (9,)
Size: 9
Data Type : int64


2. Generate a Matrix with Random Values
    Generate a 4x5 NumPy array with random integers between 1 and 100.

    Find the maximum and minimum values, along with their indices.
    


In [ ]:
arr2 = np.random.randint(1,100,(4,5))
print("\n2. Random Matrix: \n", arr2)
print("Maximum:", arr2.max(), "at index", np.unravel_index(arr2.argmax(), arr2.shape))
print("Minimum:", arr2.min(), "at index", np.unravel_index(arr2.argmax(), arr2.shape))


2. Random Matrix: 
 [[ 3 48 70 91 32]
 [22 69 62 68 53]
 [50 12 73 56 83]
 [37 17 76 95 23]]
Maximum: 95 at index (np.int64(3), np.int64(3))
Minimum: 3 at index (np.int64(3), np.int64(3))


3. Reshape an Array
    Create a 1D array of numbers from 1 to 24, then reshape it into a 4x6 matrix.

    Extract the 2nd row and 3rd column.

In [ ]:
arr3 = np.arange(1,25).reshape(4,6)
print("\n3. Reshaped Array:\n", arr3)
print("2nd Row : ", arr3[1, :])
print("3rd Column : ", arr3[:, 2])


3. Reshaped Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
2nd Row :  [ 7  8  9 10 11 12]
3rd Column :  [ 3  9 15 21]


4. Boolean Indexing
    Given a NumPy array of 15 random integers between 0 and 50, find all elements greater than 25 and replace them with -1.

In [ ]:
arr4 =np.random.randint(0,51,15)
print("Original Array : ", arr4)
arr4[arr4 > 25] = -1
print("Modified array : ", arr4)


Original Array :  [25 50 35 12 42 44 29 15 21 22 36  0  6 13 41]
Modified array :  [25 -1 -1 12 -1 -1 -1 15 21 22 -1  0  6 13 -1]


5. Mathematical Operations
    Create two 1D NumPy arrays:
    a = [1, 2, 3, 4, 5] and b = [10, 20, 30, 40, 50]

    Perform element-wise addition, subtraction, multiplication, and division.


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])
print("\5. Addition : ", a+b)
print("Subtraction : ", a-b)
print("Multiplication: ", a*b)
print("Division: ", a/b)


. Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


6. Statistical Computations
    Generate a 5x5 matrix with random floats between 0 and 1.

    Compute the mean, median, variance, and standard deviation.

In [ ]:
arr6 = np.random.rand(5,5)
print("\n6. Random 5x5 Matrix:\n", arr6)
print("Mean:", arr6.mean())
print("Median:", np.median(arr6))
print("Variance:", arr6.var())
print("Standard Deviation:", arr6.std())


6. Random 5x5 Matrix:
 [[0.84166227 0.83750433 0.82532445 0.91394684 0.25624928]
 [0.1633003  0.14618028 0.00322522 0.52767411 0.94297706]
 [0.12045981 0.51589305 0.33979219 0.75899246 0.96755249]
 [0.43712265 0.99546934 0.43102492 0.21557196 0.83984031]
 [0.68176467 0.25019177 0.94095658 0.29954529 0.12410177]]
Mean: 0.5350529355585896
Median: 0.5158930481592192
Variance: 0.10385890561351227
Standard Deviation: 0.3222714781259928


7. Matrix Multiplication
    Create two matrices:

    A is 3x2 with values from 1 to 6.

    B is 2x3 with values from 7 to 12.
    Perform matrix multiplication (A @ B) and display the result.

In [ ]:
A = np.arange(1,7).reshape(3,2)
B = np.arange(7,13).reshape(2,3)
print("\n7. Matrix A:\n", A)
print("Matrix B:\n", B)
print("\n7. Matrix Multiplication:\n", A@B)


7. Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]

7. Matrix Multiplication:
 [[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


8. Slice and Modify
    Create a 6x6 array of integers from 1 to 36.

    Extract the 3x3 sub-matrix from the center and set all its values to 0.

In [ ]:
arr8 = np.arange(1,37).reshape(6,6)
print("\n8. Original 6x6 Matrix:\n", arr8)
arr8[2:5, 2:5] = 0
print("Modified Matrix with center 3x3 set to 0:\n", arr8)


8. Original 6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Modified Matrix with center 3x3 set to 0:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14  0  0  0 18]
 [19 20  0  0  0 24]
 [25 26  0  0  0 30]
 [31 32 33 34 35 36]]


9. Use of np.where
    Create a NumPy array with values [5, 10, 15, 20, 25].

    Replace all elements greater than 15 with 99, otherwise replace with 0.

In [ ]:
arr9 = np.array([5,10,25,20,25])
arr9_result = np.where(arr9 >15, 99, 0)
print("\n9. np.where Result:", arr9_result)


9. np.where Result: [ 0  0 99 99 99]


10. Broadcasting Example
    Create a 4x4 array filled with 10s.

    Subtract a 1D array [0, 1, 2, 3] from each row using NumPy broadcasting.

In [ ]:
arr10 = np.full((4,4), 10)
arr10_result = arr10 - np.array([0,1,2,3])
print("\n10. Broadcasting Result:\n", arr10_result)


10. Broadcasting Result:
 [[10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]]
